spring:
  datasource:
    url: jdbc:mysql://121.5.5.83:3306/soupbun?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Liuchang15050
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create  # 启动时创建表

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 启用 SQL 日志
  mapper-locations: classpath*:/mapper/**/*.xml  # 配置 MyBatis XML 映射文件的位置
  typeAliasesPackage: com.soupbun.soupbunapi.model  # 配置 MyBatis 的实体类扫描路径
